service: always-onward
provider:
  name: aws
  runtime: nodejs12.x
  cfnRole: arn:aws:iam::718523126320:role/serverless
  stage: prod

functions:
  app:
    handler: handler.always-onward
    events:
        - http: ANY /
        - http: 'ANY {proxy+}'
plugins:
  - serverless-offline
