name: Deploy
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - live
jobs:
 build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Configure NPM
        run: |
          npm install
          npm test
          cd lambda
          npm install

      #~ - name: Create env file
        #~ run: |
          #~ touch .env
          #~ echo LWA_CLIENT_ID=${{ secrets.LWA_CLIENT_ID }} >> .env
          #~ echo LWA_CLIENT_SECRET=${{ secrets.LWA_CLIENT_SECRET }} >> .env
          #~ cat .env

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          LWA_CLIENT_ID: ${{ secrets.LWA_CLIENT_ID }}
          LWA_CLIENT_SECRET: ${{ secrets.LWA_CLIENT_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: |
          npm run cdk-deploy

